import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Navbar } from '@/components/layouts/Navbar';
import { Footer } from '@/components/layouts/Footer';
import { products } from '@/libs/statics';
import { InfiniteCarousel } from '@/components/elements/InfiniteCarousel';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Next Ecommerce',
	description: 'Generated by create next app',
	icons: {
		icon: './favicon.ico',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Navbar />
				<div className='py-10 block'>
					{children}
					<div className='mt-2 max-h-[200px]'>
						<div className='w-full overflow-x-auto pb-6 pt-1'>
							{products && (
								<InfiniteCarousel products={products} />
							)}
						</div>
					</div>
				</div>
				<Footer />
			</body>
		</html>
	);
}
